Create commit-tests.yml
recruitment-process/recruitment-process-back pull request #13
Opened 2023-07-18 12:33 UTC by DOSuzer

Проверка кода на соответствие PEP8 и прохождение тестов

2023-07-19 03:20 UTC, margoloko requested changes

2023-07-19 03:20 UTC, margoloko commented on .github/workflows/commit-tests.yml
> +  push:
Предлагаю сразу исключить файлы при изменении которых, проверка будет излишней практикой (типа readme)
```
on:
  push:
    paths-ignore:
      - '**.md'
```

2023-07-19 07:39 UTC, DOSuzer commented on .github/workflows/commit-tests.yml
> +  push:
сделал

2023-07-20 06:33 UTC, margoloko approved these changes

2023-07-20 11:59 UTC, merged