configured pre-commit
recruitment-process/recruitment-process-back pull request #16
Opened 2023-07-19 08:28 UTC by margoloko

Настроены pre-commit hooks. Настроены только начальные значения, для проверки работоспособности. Далее функционал будет дополнен.
В README.md описан процесс установки и запуска pre-commit.

2023-07-19 10:03 UTC, DOSuzer commented
Тогда из actions удалить проверку, или пускай и то и то будет?

2023-07-19 10:57 UTC, margoloko commented
Да пусть будет. Надо будет у ревьюеров уточнить этот вопрос. Я просто видела, что и там и там проверки делают. Не знаю, как правильно

2023-07-19 13:14 UTC, DOSuzer requested changes

2023-07-19 13:14 UTC, DOSuzer commented on requirements.txt
> +pre-commit
Наверное стоит указать версию, чтобы у всех было одинаково. Мало ли у кого другую подтянет pip.

2023-07-20 06:14 UTC, margoloko commented
добавила проверку с помощью isort и black

2023-07-20 12:01 UTC, DOSuzer approved these changes

2023-07-20 12:03 UTC, merged