Feature/vacancy
recruitment-process/recruitment-process-back pull request #21
Opened 2023-07-21 15:04 UTC by mishatar

2023-07-21 18:45 UTC, DOSuzer requested changes

2023-07-21 18:45 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +class Company(models.Model):
я бы сюда добавил не обязательные поля еще: вебсайт, email, телефон, контакт HR

2023-07-21 18:45 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +    schedule_work = MultiSelectField(
MultiSelectField надо тестировать будет, а то у пакета заявлена поддержка Django 3 и Python 3.8

2023-07-21 18:45 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +class Vacancy(models.Model):
Я думаю стоит добавить: 
company = models.ForeignKey(Company, on_delete=models.CASCADE, verbose_name='Компания', related_name='vacancys')
author = models.ForeignKey(Users, on_delete=models.CASCADE, verbose_name='Автор', related_name='vacancys')
Автора добавил чисто чтобы была связь, кто создал вакансию (например если в одной компании будет 2 ХР зарегано) и что бы проще было получить вакансии созданные конкретным ХР через user.vacancys

2023-07-21 18:45 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +class Vacancy(models.Model):
возможно вместо on_delete=models.CASCADE лучше on_delete=models.SET_NULL, null=True

2023-07-22 04:37 UTC, margoloko commented on crm_backend/recruitment/models.py
> +    EXPERIENCE = (
Константы можно будет забрать из constants_choices_resume.py. После того, как Иван вольёт свой PR

2023-07-22 10:59 UTC, mishatar commented on crm_backend/recruitment/models.py
> +    schedule_work = MultiSelectField(
протестил, вроде все работает

2023-07-22 10:59 UTC, mishatar commented on crm_backend/recruitment/models.py
> +class Vacancy(models.Model):
добавил

2023-07-22 10:59 UTC, mishatar commented on crm_backend/recruitment/models.py
> +class Company(models.Model):
добавил

2023-07-22 11:57 UTC, DOSuzer approved these changes

2023-07-22 11:57 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +class Company(models.Model):
Возможно стоит для полей адреса, телефона, email поставить null=True blank=True, так как не все компании захотят указывать эти данные.

2023-07-24 03:54 UTC, margoloko approved these changes

2023-07-25 11:52 UTC, merged