feature: Добавленны модели <Резюме> и сопутствующие модели <Опыт рабо…
recruitment-process/recruitment-process-back pull request #22
Opened 2023-07-21 19:35 UTC by ivan-hedgehog

…ты> <Информация об образовании>,добавлена регистрация этих моделей а админ, добавлен в сеттинг в INSTALLED_APPS - 'multiselectfield'(не забываем установить командой pip install django-multiselectfield), добавлена в зависимости запись о 'multiselectfield', добавлен файл константами перебора choices

2023-07-22 04:26 UTC, margoloko commented on crm_backend/recruitment/models.py
> +    dateEnd = models.DateField(
можно добавить валидатор, который будет проверять, что дата увольнения не может быть раньше даты выхода на работу

2023-07-22 04:26 UTC, margoloko commented on crm_backend/recruitment/models.py
> +    dateStart = models.DateField(verbose_name='Дата устроения')
Имена переменных рекомендуют писать в формате snake_case, а не CamelCase. 
date_start
date_end

2023-07-22 04:26 UTC, margoloko commented on crm_backend/recruitment/models.py
> +class Work_experience(models.Model):
CamelCase обычно используется для названий классов
WorkExperience

2023-07-22 04:26 UTC, margoloko commented on crm_backend/recruitment/models.py
> +class Applicant_resume(models.Model):
тоже CamelCase

2023-07-22 07:38 UTC, DOSuzer requested changes

2023-07-22 07:38 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +class Work_experience(models.Model):
Нужно добавить поле user, т.к. опыт работы относится к конкретному соискателю. Плюс у человека может быть несколько предыдущих работ. И добавь related_name чтобы проще было получать весь опыт пользователя.

2023-07-22 07:38 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +class Education(models.Model):
Тоже нужно добавить связь с пользователем я думаю

2023-07-22 07:38 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +        settings.AUTH_USER_MODEL,
если модель user берешь из settings, тогда удали импорт с 8 строки. надо оставить либо то либо то.

2023-07-24 07:18 UTC, margoloko requested changes

2023-07-24 07:18 UTC, margoloko commented on crm_backend/recruitment/models.py
> +class Work_Experience(models.Model):
CamelCase

2023-07-24 07:18 UTC, margoloko commented on crm_backend/recruitment/models.py
> +class Applicant_Resume(models.Model):
CamelCase

2023-07-24 07:18 UTC, margoloko commented on crm_backend/recruitment/admin.py
> +class Applicant_ResumeAdmin(admin.ModelAdmin):
CamelCase

2023-07-24 08:55 UTC, margoloko approved these changes

2023-07-24 09:04 UTC, DOSuzer approved these changes

2023-07-25 17:58 UTC, merged