add models candidate&commit
recruitment-process/recruitment-process-back pull request #66
Opened 2023-08-20 18:19 UTC by mishatar

2023-08-21 16:21 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +class Candidate(models.Model):
нужно добавить поле текущая должность, т.к. в фигме оно присутствует.
![image](https://github.com/recruitment-process/recruitment-process-back/assets/111976369/29d23d10-e63c-4c4b-b205-0b0ccdd2d852)

2023-08-21 16:21 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +class Comment(models.Model):
я думаю надо переименовать из коммента в заметку (возможно Note?), т.к. есть заметка, а к ней можно оставить коммент. видимо нужна еще одна модель. либо попросить дизайнеров оставить чисто заметки.
![image](https://github.com/recruitment-process/recruitment-process-back/assets/111976369/df2c50a6-51d5-40e8-8bc6-94aafa0e5931)

2023-08-22 07:10 UTC, margoloko approved these changes

2023-08-22 13:02 UTC, mishatar commented on crm_backend/recruitment/models.py
> +class Candidate(models.Model):
Исправил

2023-08-22 13:02 UTC, mishatar commented on crm_backend/recruitment/models.py
> +class Comment(models.Model):
Исправил на Note и добавил модель ответа на заметку

2023-08-22 13:22 UTC, DOSuzer approved these changes

2023-08-22 13:22 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +        Candidate, on_delete=models.CASCADE, related_name="Кандидат"
related_name="Кандидат" по русски разве сработает? или имелось ввиду verbose_name? тоже самое на строке 454

2023-08-22 13:22 UTC, DOSuzer approved these changes

2023-08-24 09:13 UTC, DOSuzer requested changes

2023-08-24 09:13 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +class Candidate(models.Model):
Еще такой момент, как я понял это: заходя на страницу вакансии HR на текущий момент сам добавляет кандидата в систему и этот кандидат будет именно на данную вакансию. Соответственно нужна еще связь кандидат-вакансия, чтобы понимать кто к какой вакансии относится. Поэтому я бы добавил поле 
vacancy = models.ForeignKey(
        Vacancy,
        on_delete=models.CASCADE,
        verbose_name="Вакансия",
        related_name="candidates",
    )

2023-08-25 09:26 UTC, merged