feature: добавлена модели Technology и TechnologyStack для окна Match
recruitment-process/recruitment-process-back pull request #83
Opened 2023-08-27 11:05 UTC by G-Bedy

Создал модель Technology содержащую список технологий - пример: (Python, Java, GS, Django, ...)
Создал модель TechnologyStack содержащую два поля 1. Технологию и 2. Срок работы по технологии - пример:
(Python 3 года,  Java 1 год, Django 7 лет, ...)
Добавил в модели Vacancy и Candidate поле technology_stack - ForeignKey к модели TechnologyStack.
Таким образом в моделях Вакансии и Кандидат будут поля содержащие информацию:
- для модели вакансии необходимый стек и опыт работы - Python 3 года
- для модели кандидат имеющийся стек и опыт работы - Python 2 года

Далее из этих данных фронт на клиентской части будет считать Match

PS
Отдельную модель Technology (список технологий) создал чтобы не создавались повторные навыки в модели TechnologyStack. Таким образом можно избежать дублирования навыков.

2023-08-27 14:32 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +class Technology(models.Model):
Я бы только назвал не Technology а может Skill, у руководителя какого-нибудь нужен навык управления командой от 5 лет. Тоже самое с TechnologyStack - SkillStack.

2023-08-27 14:32 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +    technology_stack_time = models.IntegerField()
я бы добавил null=True, т.к. какой-нибудь навык типо коммуникабельность, важный для секретаря, не имеет срока.

2023-08-27 14:32 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +class TechnologyStack(models.Model):
Как я понимаю связь должна быть обратной той которую ты сделал, т.к. например в вакансии в поле technology_stack будет хранится максимум один FK, а нам нужен список. Также у нас связь может быть как с вакансией, так и с кандидатом, поэтому я бы попробовал сделать как здесь описано: https://docs.djangoproject.com/en/4.1/ref/contrib/contenttypes/#id1
добавить в эту модель поля:

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    class Meta:
        indexes = [
            models.Index(fields=["content_type", "object_id"]),
        ]
тогда чтобы получить весь стек по вакансии/кандидату будем использовать:
SkillStack.objects.filter(content_object=vacancy)
SkillStack.objects.filter(content_object=candidate)

Сам так не делал но походу это наш случай)

2023-08-28 06:31 UTC, margoloko commented on crm_backend/recruitment/models.py
> +class Technology(models.Model):
Поддерживаю

2023-08-28 06:46 UTC, margoloko requested changes

2023-08-28 06:46 UTC, margoloko commented on crm_backend/api/apps.py
> +    """App config."""
Давай придерживаться одного формата - документируем на русском - """Настройка приложения API."""

2023-08-28 06:46 UTC, margoloko commented on crm_backend/recruitment/apps.py
> +    """Модель найма."""
может лучше: """Настройка приложения Recruitment."""

2023-08-28 06:46 UTC, margoloko commented on crm_backend/users/apps.py
> +    """Модель Юзер."""
Настройка приложения Users

2023-08-28 06:46 UTC, margoloko commented on crm_backend/recruitment/models.py
> +        verbose_name = "Стек и срок работы"
Тогда здесь тоже логично поправить со Стек на скиллы или требования

а срок работы-может лучше опыт?

2023-08-28 06:46 UTC, margoloko commented on crm_backend/recruitment/models.py
> +    """Модель для списка технологий."""
"""Модель для списка требований."""

2023-09-09 07:43 UTC, margoloko approved these changes

2023-09-09 16:24 UTC, DOSuzer commented on crm_backend/recruitment/admin.py
> +        "technology_stack",
здесь тоже же будет skill_stack?

2023-09-09 16:24 UTC, DOSuzer commented on crm_backend/recruitment/admin.py
> +        "technology_stack",
skill_stack?

2023-09-09 16:24 UTC, DOSuzer commented on crm_backend/recruitment/models.py
> +    technology_stack = models.ForeignKey(
может ManyToMany, или обратную связь сделать? а то получается ссылка будет на одну запись со скилом и сроком

2023-09-14 06:37 UTC, merged